---
# tasks file for redmine

- name: Install required packages
  package: name="{{redmine_packages}}" state=present

- name: Download redmine source
  git:
    repo: "{{redmine_url}}"
    dest: "{{redmine_checkout_path}}"
    version: "{{redmine_version}}"
    depth: 1
    force: true
  become: true
  become_user: "{{rails_app_user}}"

- name: Enable version as current
  file:
    src: "{{redmine_checkout_path}}"
    dest: "{{rails_app_path}}"
    owner: "{{rails_app_user}}"
    group: "{{rails_app_user}}"
    state: link

- name: Create shared configuration/data folders
  file:
    path: "{{item}}"
    owner: "{{rails_app_user}}"
    group: "{{rails_app_user}}"
    state: directory
  loop:
    - "{{redmine_log_shared_path}}"
    - "{{redmine_files_shared_path}}"
    - "{{redmine_repos_shared_path}}"
    - "{{redmine_config_shared_path}}"

- name: Create configuration file
  template:
    src: configuration.yml
    dest: "{{redmine_config_shared_path}}/configuration.yml"
    owner: "{{rails_app_user}}"
    group: "{{rails_app_user}}"

- name: Link shared configuration files
  file:
    src: "{{rails_app_config_path}}/{{item}}"
    dest: "{{rails_app_path}}/config/{{item}}"
    owner: "{{rails_app_user}}"
    group: "{{rails_app_user}}"
    state: link
  loop:
    - "{{rails_app_config_path_db | basename}}"
    - "{{rails_app_config_path_puma | basename}}"
    - configuration.yml

- name: Install required gems
  command: bundle install --without development test --path={{rubygems_path}}
  args:
    chdir: "{{rails_app_path}}"
    creates: "{{rails_app_path}}/Gemfile.lock"
  environment:
    PATH: "{{rubygems_path}}/bin:{{ ansible_env.PATH }}"
  become: true
  become_user: "{{rails_app_user}}"

- name: Session store secret generation
  command: bundle exec rake generate_secret_token
  args:
    chdir: "{{rails_app_path}}"
    creates: "{{rails_app_path}}/config/secret_token.rb"
  environment:
    PATH: "{{rubygems_path}}/bin:{{ ansible_env.PATH }}"
  become: true
  become_user: "{{rails_app_user}}"

- name: Run database migrations
  command: bundle exec rake db:migrate
  args:
    chdir: "{{rails_app_path}}"
    creates: "{{rails_app_path}}/db/schema.rb"
  environment:
    PATH: "{{rubygems_path}}/bin:{{ ansible_env.PATH }}"
  become: true
  become_user: "{{rails_app_user}}"

- name: Redmine database default data set
  command: bundle exec rake redmine:load_default_data
  args:
    chdir: "{{rails_app_path}}"
  environment:
    PATH: "{{rubygems_path}}/bin:{{ ansible_env.PATH }}"
    REDMINE_LANG: "{{redmine_lang}}"
  become: true
  become_user: "{{rails_app_user}}"

- name: File system permissions
  file:
    path: "{{rails_app_path}}/{{item}}"
    owner: "{{rails_app_user}}"
    group: "{{lighttpd_user}}"
    mode: 0755
  with_items:
    - tmp
    - tmp/pdf
    - files
    - public/plugin_assets
