---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: redmine-ubuntu-18.04
    image: ubuntu:18.04
    volumes:
      - "/mnt/mirrors/ubuntu/18.04:/var/cache/apt/archives"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../common/playbook.yml
    verify: ../common/verify.yml
  env:
    RAILS_APP_DB: postgresql
    RAILS_APP_PROXY: apache2
  lint:
    name: ansible-lint
scenario:
  name: apache2
verifier:
  name: goss
  lint:
    name: yamllint
